language: node_js
node_js:
  - "4"

before_script:
  - npm install @angular/cli -g
  - npm install -g karma
  - npm install -g gulp
  - npm install

notifications:
  email:
    recipients:
      - dcampos@vmware.com
      - juli@vmware.com
      - aspear@vmware.com
    on_success: never # default: change
    on_failure: always # default: always
